name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/Personal-Portfolio

            git pull origin main

            cd portfolio-vite

            docker build -t portfolio-vite .

            docker stop portfolio-app || true

            docker rm portfolio-app || true

            docker run -d \
              --name portfolio-app \
              --restart unless-stopped \
              -p 81:80 \
              portfolio-vite
              